services:
  # =========================================
  # TRAEFIK (El Proxy Dinámico)
  # =========================================
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: unless-stopped
    environment:
      - DOCKER_API_VERSION=1.41
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"

      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=ezequiel2014.edlv@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"

      - "--accesslog=true"
      - "--accesslog.format=json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt

  # =========================================
  # BACKEND (La API)
  # =========================================
  backend-portfolio:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-2.amazonaws.com/portfolio-sre-backend:prod
    container_name: backend-portfolio
    restart: unless-stopped
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.backend.rule=Host(`api.ez-lab.site`) && PathPrefix(`/api/health`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=8585"

  # =========================================
  # FRONTEND (La Web Visible)
  # =========================================
  frontend-portfolio:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-2.amazonaws.com/portfolio-sre-frontend:prod
    container_name: frontend-portfolio
    restart: unless-stopped
    depends_on:
      - backend-portfolio
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`ez-lab.site`) || Host(`www.ez-lab.site`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  # =========================================
  # WATCHTOWER (El Agente GitOps AWS)
  # =========================================
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    environment:
      - AWS_REGION=us-east-2
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_CLEANUP=true
      - DOCKER_API_VERSION=1.40
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/infra-web/ecr-cred.json:/config.json:ro

  # =========================================
  # BASE DE DATOS LOCAL (FinOps)
  # =========================================
  db-vaultwarden:
    image: postgres:16-alpine
    container_name: db-vaultwarden
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=myssticwarden
    volumes:
      - db_data:/var/lib/postgresql/data

  # =========================================
  # VAULTWARDEN (Gestor de Contraseñas Privado)
  # =========================================
  vaultwarden:
    image: vaultwarden/server:1.32.0
    container_name: vaultwarden
    restart: unless-stopped
    depends_on:
      - db-vaultwarden
    environment:
      - AWS_REGION=us-east-2
      - VT_LOG_LEVEL=info
      - SIGNUPS_ALLOWED=false
      - WEB_VAULT_ENABLED=true
      # Apuntamos al contenedor local 'db-vaultwarden' en el puerto 5432
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db-vaultwarden:5432/myssticwarden
    volumes:
      - ./vaultwarden-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vault.rule=Host(`vault.ez-lab.site`)"
      - "traefik.http.routers.vault.entrypoints=websecure"
      - "traefik.http.routers.vault.tls.certresolver=letsencrypt"
      - "traefik.http.services.vault.loadbalancer.server.port=80"
      - "traefik.http.routers.vault.middlewares=vault-whitelist"
      - "traefik.http.middlewares.vault-whitelist.ipwhitelist.sourcerange=100.64.0.0/10,172.16.0.0/12"

  # ---------------------------------------------------
  # TELEMETRÍA SRE (MyssTic Sentinel Agents)
  # ---------------------------------------------------
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
      - ./GeoLite2-City.mmdb:/etc/promtail/GeoLite2-City.mmdb:ro
    command: -config.file=/etc/promtail/config.yml

volumes:
  db_data: