- name: Crear directorio de la app
  ansible.builtin.file:
    path: /opt/infra-web
    state: directory
    owner: admin
    group: docker
    mode: '0755'

- name: Copiar compose al servidor
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/infra-web/docker-compose.yml
    mode: '0644'

- name: Copiar configuración de Promtail
  template:
    src: promtail-config.yml.j2
    dest: /opt/infra-web/promtail-config.yml
    mode: '0644'

- name: Asegurar que el CLI de AWS esté instalado para el handshake
  ansible.builtin.apt:
    name: awscli
    state: present
    update_cache: yes
  become: true

#- name: Recuperar credenciales de la base de datos desde AWS Secrets Manager
#  shell: "aws secretsmanager get-secret-value --secret-id mysstic-db-credentials --region us-east-2 --query SecretString --output text"
#  register: db_secret_raw
#  delegate_to: localhost
#  changed_when: false
#  become: false

#- name: Parsear credenciales del JSON cifrado
#  set_fact:
#    db_credentials: "{{ db_secret_raw.stdout | from_json }}"

- name: Asegurar que el archivo .env de producción tenga las credenciales dinámicas
  template:
    src: templates/env.j2
    dest: /opt/infra-web/.env
    mode: '0600'
  become: true

- name: 🌍 Descargar base de datos MaxMind GeoLite2 (Para Analytics)
  ansible.builtin.get_url:
    url: https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-City.mmdb
    dest: /opt/infra-web/GeoLite2-City.mmdb
    mode: '0644'
    owner: admin
    group: docker

- name: Desplegar contenedores (Traefik + Portfolio + Vaultwarden)
  community.docker.docker_compose_v2:
    project_src: /opt/infra-web
    state: present
    pull: missing
  become: true
