name: CI SecOps - MyssTic Cloud IaC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  # =====================================================================
  # FASE 0: AUDITORÍA DE PIPELINE (Meta-Seguridad)
  # =====================================================================
  workflow-lint:
    name: Validar YAML del Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: 1. Clonar el repositorio
        uses: actions/checkout@v4

      - name: 2. Validar sintaxis de GitHub Actions
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color

  # =====================================================================
  # FASE CI: SEGURIDAD Y AUDITORÍA
  # =====================================================================
  security-and-linting:
    name: Escaneo Zero-Trust y Linting
    runs-on: ubuntu-latest
    needs: workflow-lint
    steps:
      - name: 1. Clonar el repositorio
        uses: actions/checkout@v4

      - name: 2. Escaneo de Secretos (Trufflehog)
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ""
          head: ${{ github.sha }}
          extra_args: --debug --only-verified

      - name: 3. Auditoría IaC (Checkov)
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
          soft_fail: false

  # =====================================================================
  # FASE CD: DESPLIEGUE CONTINUO
  # =====================================================================
  cd-deploy:
    name: 🚀 Despliegue Automático (Terraform + Ansible)
    runs-on: ubuntu-latest
    needs: security-and-linting
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: 1. Clonar el repositorio
        uses: actions/checkout@v4

      - name: 2. Autenticación Zero-Trust en AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-2

      - name: 3. Configurar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: 4. Terraform Init & Apply (Infraestructura inmutable)
        working-directory: ./terraform
        run: |
          terraform init
          terraform apply -auto-approve

#      - name: 4.5. Extraer Outputs de Terraform para Ansible
#        working-directory: ./terraform
#        run: |
#          DB_ENDPOINT="$(terraform output -raw database_endpoint)"
#          echo "DB_ENDPOINT=$DB_ENDPOINT" >> "$GITHUB_ENV"

      - name: 5. Extraer Tailscale Auth Key de AWS Secrets Manager
        id: fetch-ts-key
        run: |
          TS_KEY=$(aws secretsmanager get-secret-value --secret-id mysstic-core-secrets --query SecretString --output text | jq -r .tailscale_auth_key)
          echo "::add-mask::$TS_KEY"
          echo "TS_AUTHKEY=$TS_KEY" >> "$GITHUB_ENV"

      - name: 6. Conectar GitHub Runner a VPN Tailscale Zero-Trust
        uses: tailscale/github-action@v2
        with:
          version: "1.98.4"
          oauth-client-id: ""
          oauth-secret: ""
          authkey: ${{ env.TS_AUTHKEY }}
          tags: tag:mysstic

      - name: 7. Esperar inicialización del SO (Evitar Race Condition)
        run: |
          echo "Terraform terminó, pero Linux y Tailscale en la EC2 siguen instalándose."
          echo "Esperando 90 segundos para que MagicDNS propague el hostname..."
          sleep 90

      - name: 8. Ejecutar Ansible Playbook vía Tailscale SSH
        env:
          AWS_ACCOUNT_ID: "${{ secrets.AWS_ACCOUNT_ID }}"
#          DB_ENDPOINT: "${{ env.DB_ENDPOINT }}"
          DB_PASSWORD: "${{ secrets.DB_PASSWORD }}"
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          export ANSIBLE_REMOTE_USER=admin

          pip3 install boto3 botocore
          ansible-galaxy collection install amazon.aws

          ansible-playbook -i ansible/inventory/aws_ec2.yml ansible/site.yml -e "aws_account_id=${AWS_ACCOUNT_ID}" -e "db_password=${DB_PASSWORD}"